### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by snax44** [EONRaider/BCA-Phantom#6]
Hi !

First of all, thank you very much for this great tool !

I'm trying to build binary with self signed certs (made with your script).
Unfortunately the build doesn't work and python return an error I don't understand.

```
$python build.py server --server-cert server-cert.pem
Traceback (most recent call last):
  File "build.py", line 38, in <module>
    def server(args: argparse.Namespace) -> list[str]:
TypeError: 'type' object is not subscriptable
```

Hope this question is not to stupid.
Thanks in advance for your help.

**Comment by EONRaider** [comment]
Hey. This is not a build error. Type hinting subscriptions is a Python 3.9 feature. All you have to do is execute the build.py file with a 3.9+ interpreter.

**Comment by snax44** [comment]
OK thank you for your help.
